# compile it in quartus first

aero-rtf.jam: Top.pof
	quartus_cpf -c Top.pof aero-rtf.jam

clean:
	rm -rf *.rpt *.chg smart.log *.htm *.eqn *.pin *.sof *.pof *.smsg *.summary *.jdi *.sld db incremental_db output_files *.jam *.done *.qws *.qdf db/ RTL/*.v.bak
